### ISSUE TITLE
Take ownership constructors for wrapper types

### ISSUE THREAD

**Issue by JeremyAgost** [macmade/CFPP#17]
I can envision a factory function for CFPP types conceptually similar to CFBridgingRelease from ARC-enabled Objective-C. The purpose of which is to assign a CF object to a wrapper and release it. The most obvious benefit would be the ability to write code like `CF::Array components = CFStringCreateArrayBySeparatingStrings(NULL, string, separator)`.

I'm planning on using CFPP in a project and I'm probably going to implement this functionality for that purpose. If you aren't opposed to the idea on principle I'd be happy to Pull Request it.

**Comment by macmade** [comment]
Thanks a lot for the request. : )

I'm not opposed at all to such kind of feature. In fact I recently introduced a new class to deal with those ownership issues: `CF::AutoPointer`.

I've checked the code in your pull request (#18), and at first sight it seems redundant.

`CF::AutoPointer` can be used for all standard CoreFoundation types, even those not available in CoreFoundation++, as well as types from other frameworks:

    {
        CFStringRef     o1 = CFStringCreateWith...();
        CFMachPortRef   o2 = CFMachPortCreate();
        CF::AutoPointer ap( o1 );
        
        ap = o2; /* `o1` is released as another pointer is assigned */
        
    } /* `o2` is released as `ap` is destroyed */
    
It basically works the same way as `std::shared_ptr`, meaning you can safely copy them, use them as functions' parameters or return types:

    CFStringRef     s1  = CFStringCreateWith...();
    CF::AutoPointer ap1 = s1;
    CF::AutoPointer ap2 = ap1;
    
    CF::AutoPointer Some::Func( void )
    {
        return CFStringCreateWith...();
    }
    
    void Some::Func( CF::AutoPointer ap );
    
    {
        Some::Func( CFStringCreateWith...() );
    }
    
`CF::AutoPointer` also includes a generic `As` method, so you can get the original pointer back:
    
    
    CF::AutoPointer ap = CFStringCreateWith...();
    CFStringRef     s  = ap.As< CFStringRef >();
        
Now, as extra sugar, the `As` method can also be used to get CoreFoundation++ objects:

    CF::String s = CF::AutoPointer( CFStringCreateWith...() ).As< CF::String >();
    
I'll let you check this and see if it can work for your project.

I'm leaving the issue and pull request opened for now. : )

Cheers,

**Comment by JeremyAgost** [comment]
Yeah that's definitely another syntactic way to accomplish a similar goal. Downside is of course that when you go to use it you have to specify the casting type. That's why I wrote the metafunc stuff, so I could have implicit casting :)

**Comment by macmade** [comment]
Well, in fact you don't need to specify the type if you use the `GetCFObject` method, as all CF++ wrappers include constructors and assignment operators for `CFTypeRef` and checks the type ID. So you could also use:

    CF::String s = CF::AutoPointer( CFStringCreateWithCString( NULL, "hello, world", kCFStringEncodingASCII ) ).GetCFObject();

**Comment by JeremyAgost** [comment]
Fair enough. I still like my function better because it requires one less keyword ;)

**Comment by macmade** [comment]
Agree : )

`CF::AutoPointer` already has a typecast operator for `CFTypeRef` as it inherits from `CF::Type`.
Unfortunately, it can't be used implicitly in such a context because of the overload resolution rules, hence the need to call `GetCFObject` or to use a `static_cast`.

Best solution IMHO would be to declare constructors and assignment operators taking a `const AutoPointer &`.

I was thinking about a more generic approach for all wrapper classes, so the amount of boilerplate code can be reduced (eg. having a CF::Type< T > base).
This could declare all constructors for `CFTypeRef`, `T`, `AutoPointer`, etc.

**Comment by macmade** [comment]
Got a few things like that in a local branch... I'll try to clean this up and push it so you can take a look. : )

**Comment by JeremyAgost** [comment]
Mmm, I was just using this today and thinking “man I could really use a CF::Type<T>” especially since my project uses a lot of custom CF-style types

**Comment by macmade** [comment]
Sure this would be great in order to support custom CF types.
And a lot easier to write wrappers for those types.

I'm going to complete the unit tests for all constructors/assignment operators, so I can safely introduce this feature, hopefully next week.

**Comment by mihairichard** [comment]
Consider using a template type
```
template <typename T>
class NoRetainType {
public:
   T *ref;
   NoRetainType(T *r):ref(r){}
};
```
used along with a macro to make code more readable

```
#define NO_RETAIN_CAST(x) NoRetainType<decltype(x)>(x)
```
and let your other constructors know that when taking a NoRetainType to not do the usual CFRetain() when assigning. (i.e. `CF::String  s1 = NO_RETAIN_CAST(CFStringCreateWith...());`)

This macro should always be used with Create or Copy. 

Off-topic: I've also needed a C++ wrapper for some CF functionality but I'm seeing this project too late as I've already implemented my version of the wrapper. My advice is inspired from what I have in my code
