### ISSUE TITLE
Dictionary constructor doesn't take ints.

### ISSUE THREAD

**Issue by mitchellwong** [macmade/CFPP#24]
According to the readme CF::Dictionary d3( 100 ); is valid for constructing a dictionary with an initial capacity. If I do this I get error Types CF::Dictionary and int are not compatible. As well, I don't see a constructor for int in the Dictionary header.

**Comment by macmade** [comment]
Thanks a lot, this has been fixed in 2c75884b5ef059e1e084501e16406bca28143515 for `CF::Array` and `CF::Dictionary`.

**Comment by macmade** [comment]
Note that this has also been added to `CF::Data` in 6c2aaa78c3af2ff39d08d1fafad980aa243ee44a.

**Comment by mitchellwong** [comment]
"All CF::Array objects are created as mutable, and an initial capacity can be passed to the constructor:"

"Initial capacity" seems a bit misleading because the capacity of a CFType can't change once set. CoreFoundation documentation tends towards the phrase "maximum capacity", but "fixed capacity" may be more suitable.

**Comment by macmade** [comment]
That's right, I'll fix the documentation in the development branch for the next release. Thanks.
