### ISSUE TITLE
CF::String lacks a 'const unsigned char *' ctor

### ISSUE THREAD

**Issue by gregzo** [macmade/CFPP#40]
No big deal, but sqlite3_column_text returns const unsigned char *, would be a useful addition ;)

**Comment by macmade** [comment]
Mmmmmm... Not sure I like this one...

`unsigned char *` could possibly mean a completely different stuff, and an implicit conversion could lead to undefined behaviour...

This would require a `reinterpret_cast` anyway, so I don't think this should be done implicitly.
