### ISSUE TITLE
Improvement:  FromPropertyList overloads which accept CF::Data

### ISSUE THREAD

**Issue by gregzo** [macmade/CFPP#41]
Again, nice to parse blobs!

**Comment by macmade** [comment]
`FromPropertyList` takes a path. You can use `FromPropertyListString`, which takes a `std::string`, when you have the property list data.

Note that `CF::Data` declares a cast operator for `std::string`, so you can simply:

    CF::Dictionary::FromPropertyListString( CF::Data( cfDataObject ) );

Declaring a specific overload would cause some ambiguity between `CF::Data` and `std::string`.
That being said, `FromPropertyListData` could be OK.

**Comment by gregzo** [comment]
Thanks for the tip regarding the cast operator, nice!

Looking at the implementation, wouldn't this imply a lot of to and froing ? '''CF::Data''' to '''std::string''' when casting, then in the implementation of '''FromPropertyList( std::string )''', from the string back to '''CF::Data'''?

**Comment by macmade** [comment]
Yup, sure...

I think I'll go with `FromPropertyListData`, as this will be straightforward and will remove the ambiguity.

**Comment by macmade** [comment]
Added in b485abcc6bbf40f11f04f80a6192cfa47a423ffe.
