### ISSUE TITLE
Tag a version?

### ISSUE THREAD

**Issue by mactalla** [macmade/CFPP#55]
When using this library it would be quite useful to be able to reference a specific version and know what snapshot of the code it represents.

I see milestones are already used for the roadmap items.  It appears that all outstanding issues are marked for v0.3.0+.  Could we tag current master as v0.2.0 for a reference point?

**Comment by macmade** [comment]
I used to tag versions, but this quickly became annoying.  
This project is quite stable now, and having versions numbers would basically imply tagging every single commit.

I would suggest you to fork and tag as you desire.
